<<: !include _base.yaml

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      #mode: INPUT_PULLUP
      #inverted: True
    name: $name switch
    on_state:
      then:
        - light.toggle: lightid
    internal: true
    id: switchid

light:
  - platform: binary
    name: $name
    output: shelly_1_relay
    id: lightid

output:
  - platform: gpio
    pin: GPIO4
    id: shelly_1_relay