esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: $name button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: $name
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin:
    number: GPIO13
    inverted: yes